# Generated by Django 5.2.17 on 2026-09-29 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TitleGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Title saved"),
                            ("unusable", "Unusable answer"),
                            ("superseded", "Renamed during the call"),
                            ("chat_deleted", "Chat deleted during the call"),
                            ("failed", "Proxy call failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("usage_estimated", models.BooleanField(default=False)),
                (
                    "input_price_micros_per_mtok",
                    models.PositiveBigIntegerField(default=0),
                ),
                (
                    "output_price_micros_per_mtok",
                    models.PositiveBigIntegerField(default=0),
                ),
                ("cost_micros", models.BigIntegerField(default=0)),
                (
                    "error_status",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="title_generations",
                        to="chat.conversation",
                    ),
                ),
                (
                    "llm_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.llmmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "title generation (app cost)",
                "verbose_name_plural": "title generations (app cost)",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
