# Generated by Django 5.2.17 on 2026-09-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_title_generation"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="title_source",
            field=models.CharField(
                choices=[
                    ("provisional", "Provisional (first line)"),
                    ("generating", "Generating"),
                    ("auto", "Automatic"),
                    ("user", "Set by the user"),
                    ("failed", "Automatic title failed"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
