# Generated by Django 5.2.17 on 2026-09-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_title_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="include_memories",
            field=models.BooleanField(default=True),
        ),
    ]
