# Generated by Django 5.2.17 on 2026-09-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LLMModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("google", "Google"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "api_model_id",
                    models.CharField(
                        help_text="The model id sent to the proxy, e.g. gpt-5.6-luna.",
                        max_length=100,
                        unique=True,
                        verbose_name="API model id",
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("value", "Value"),
                            ("standard", "Standard"),
                            ("premium", "Premium"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                (
                    "input_price_micros_per_mtok",
                    models.PositiveBigIntegerField(
                        verbose_name="input price (µ$ per 1M tokens)"
                    ),
                ),
                (
                    "output_price_micros_per_mtok",
                    models.PositiveBigIntegerField(
                        verbose_name="output price (µ$ per 1M tokens)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "LLM model",
                "ordering": ["provider", "sort_order", "display_name"],
            },
        ),
    ]
